<?php
/**
 * FileDataSource System Class.
 *
 * @version    4.0.0
 * @package    MySource4
 * @subpackage FileDataSource
 * @author     Squiz Pty Ltd <mysource4@squiz.net>
 * @copyright  2006-2007 Squiz Pty Ltd (ABN 77 084 670 600)
 * @license    http://matrix.squiz.net/licence Squiz.Net Open Source Licence
 */

require_once 'Systems/DataSource/DataSourceSystem.inc';

/**
 * FileDataSourceSystem.
 *
 * @since 4.0.0
 */
class FileDataSourceSystem extends BaseSystem
{


    /**
     * Constructor.
     *
     * @since 4.0.0
     */
    public function __construct()
    {

    }//end __construct()


}//end class

?>
