<?php
/**
 * Float Attribute.
 *
 * @version    4.0.0
 * @package    MySource4
 * @subpackage AttributeDataSource
 * @author     Squiz Pty Ltd <mysource4@squiz.net>
 * @copyright  2006-2007 Squiz Pty Ltd (ABN 77 084 670 600)
 * @license    http://matrix.squiz.net/licence Squiz.Net Open Source Licence
 */

require_once 'Systems/DataSource/AttributeTypes/DataSourceFloat.inc';

/**
 * AttributeDataSourceFloat.
 *
 * @since 4.0.0
 */
class AttributeDataSourceFloat extends DataSourceFloat
{

}//end class

?>