<?php

require_once dirname(dirname(dirname(dirname(dirname(__FILE__))))).'/Systems/BaseSystem.inc';

/**
 * TestSys1 System.
 *
 * Installs any additional components of the TestSys1 System.
 *
 * @package MySource 4
 * @author  Squiz Pty Ltd <mysource4@squiz.net>
 */
class TestDALSys1System extends BaseSystem
{


    /**
     * Constructor.
     *
     * Private to avoid instantiation.
     *
     * @return bool
     */
    public function __construct()
    {

    }//end __construct()


}//end class


?>
