<?php
/**
 * DALBakerException.
 *
 * @version    4.0.0
 * @package    MySource4
 * @subpackage DAL
 * @author     Squiz Pty Ltd <mysource4@squiz.net>
 * @copyright  2006-2007 Squiz Pty Ltd (ABN 77 084 670 600)
 * @license    http://matrix.squiz.net/licence Squiz.Net Open Source Licence
 */

require_once dirname(__FILE__).'/DALException.inc';

/**
 * DALBakerException.
 *
 * Exception type that is thrown during the baking of XML query definitions.
 *
 * @since 4.0.0
 */
class DALBakerException extends DALException
{


}//end class

?>