<?php
/**
 * DALException.
 *
 * @version    4.0.0
 * @package    MySource4
 * @subpackage DAL
 * @author     Squiz Pty Ltd <mysource4@squiz.net>
 * @copyright  2006-2007 Squiz Pty Ltd (ABN 77 084 670 600)
 * @license    http://matrix.squiz.net/licence Squiz.Net Open Source Licence
 */

/**
 * DALException.
 *
 * Base Exception class for the Database Abstraction Layer.
 *
 * @since 4.0.0
 */
class DALException extends Exception
{


}//end class

?>