<?php
/**
 * Installer for the Attribute System.
 *
 * @version    4.0.0
 * @package    MySource4
 * @subpackage Attribute
 * @author     Squiz Pty Ltd <mysource4@squiz.net>
 * @copyright  2006-2007 Squiz Pty Ltd (ABN 77 084 670 600)
 * @license    http://matrix.squiz.net/licence Squiz.Net Open Source Licence
 */

require_once 'Systems/BaseSystem.inc';

/**
 * Attribute System Class.
 *
 * Installs any additional components of the Asset Attribute System.
 *
 * @since 4.0.0
 */
class AttributeSystem extends BaseSystem
{

}//end class

?>