# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1225595400);
user_pref("app.update.lastUpdateTime.background-update-timer", 1225595400);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1225595400);
user_pref("app.update.lastUpdateTime.microsummary-generator-update-timer", 1221493371);
user_pref("browser.migration.version", 1);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.importDefaults", false);
user_pref("browser.places.leftPaneFolderId", -1);
user_pref("browser.places.smartBookmarksVersion", 1);
user_pref("extensions.enabledItems", "{243cc1ee-c821-4544-aebb-54c44125b9aa}:0.4.1,{972ce4c6-7e08-4474-a285-3208198ce6fd}:3.0.1");
user_pref("extensions.lastAppVersion", "3.0.1");
user_pref("extensions.newAddons", "{243cc1ee-c821-4544-aebb-54c44125b9aa}");
user_pref("network.cookie.prefsMigrated", true);
user_pref("print.print_bgcolor", true);
user_pref("print.print_bgimages", true);
user_pref("print.print_footerleft", "");
user_pref("print.print_footerright", "");
user_pref("print.print_headerleft", "");
user_pref("print.print_headerright", "");
user_pref("print.print_margin_bottom", "0");
user_pref("print.print_margin_left", "0");
user_pref("print.print_margin_right", "0");
user_pref("print.print_margin_top", "0");
user_pref("print.print_printer", "PostScript/default");
user_pref("print.tmp.printerfeatures.PostScript/default.can_change_colorspace", false);
user_pref("print.tmp.printerfeatures.PostScript/default.can_change_downloadfonts", false);
user_pref("print.tmp.printerfeatures.PostScript/default.can_change_jobtitle", false);
user_pref("print.tmp.printerfeatures.PostScript/default.can_change_num_copies", true);
user_pref("print.tmp.printerfeatures.PostScript/default.can_change_orientation", true);
user_pref("print.tmp.printerfeatures.PostScript/default.can_change_paper_size", true);
user_pref("print.tmp.printerfeatures.PostScript/default.can_change_plex", false);
user_pref("print.tmp.printerfeatures.PostScript/default.can_change_printincolor", true);
user_pref("print.tmp.printerfeatures.PostScript/default.can_change_resolution", false);
user_pref("print.tmp.printerfeatures.PostScript/default.can_change_spoolercommand", true);
user_pref("print.tmp.printerfeatures.PostScript/default.colorspace.0.name", "default");
user_pref("print.tmp.printerfeatures.PostScript/default.colorspace.count", 1);
user_pref("print.tmp.printerfeatures.PostScript/default.has_special_printerfeatures", true);
user_pref("print.tmp.printerfeatures.PostScript/default.orientation.0.name", "portrait");
user_pref("print.tmp.printerfeatures.PostScript/default.orientation.1.name", "landscape");
user_pref("print.tmp.printerfeatures.PostScript/default.orientation.count", 2);
user_pref("print.tmp.printerfeatures.PostScript/default.paper.0.height_mm", 210);
user_pref("print.tmp.printerfeatures.PostScript/default.paper.0.is_inch", false);
user_pref("print.tmp.printerfeatures.PostScript/default.paper.0.name", "A5");
user_pref("print.tmp.printerfeatures.PostScript/default.paper.0.width_mm", 148);
user_pref("print.tmp.printerfeatures.PostScript/default.paper.1.height_mm", 297);
user_pref("print.tmp.printerfeatures.PostScript/default.paper.1.is_inch", false);
user_pref("print.tmp.printerfeatures.PostScript/default.paper.1.name", "A4");
user_pref("print.tmp.printerfeatures.PostScript/default.paper.1.width_mm", 210);
user_pref("print.tmp.printerfeatures.PostScript/default.paper.2.height_mm", 420);
user_pref("print.tmp.printerfeatures.PostScript/default.paper.2.is_inch", false);
user_pref("print.tmp.printerfeatures.PostScript/default.paper.2.name", "A3");
user_pref("print.tmp.printerfeatures.PostScript/default.paper.2.width_mm", 297);
user_pref("print.tmp.printerfeatures.PostScript/default.paper.3.height_mm", 279);
user_pref("print.tmp.printerfeatures.PostScript/default.paper.3.is_inch", true);
user_pref("print.tmp.printerfeatures.PostScript/default.paper.3.name", "Letter");
user_pref("print.tmp.printerfeatures.PostScript/default.paper.3.width_mm", 215);
user_pref("print.tmp.printerfeatures.PostScript/default.paper.4.height_mm", 355);
user_pref("print.tmp.printerfeatures.PostScript/default.paper.4.is_inch", true);
user_pref("print.tmp.printerfeatures.PostScript/default.paper.4.name", "Legal");
user_pref("print.tmp.printerfeatures.PostScript/default.paper.4.width_mm", 215);
user_pref("print.tmp.printerfeatures.PostScript/default.paper.5.height_mm", 431);
user_pref("print.tmp.printerfeatures.PostScript/default.paper.5.is_inch", true);
user_pref("print.tmp.printerfeatures.PostScript/default.paper.5.name", "Tabloid");
user_pref("print.tmp.printerfeatures.PostScript/default.paper.5.width_mm", 279);
user_pref("print.tmp.printerfeatures.PostScript/default.paper.6.height_mm", 254);
user_pref("print.tmp.printerfeatures.PostScript/default.paper.6.is_inch", true);
user_pref("print.tmp.printerfeatures.PostScript/default.paper.6.name", "Executive");
user_pref("print.tmp.printerfeatures.PostScript/default.paper.6.width_mm", 190);
user_pref("print.tmp.printerfeatures.PostScript/default.paper.count", 7);
user_pref("print.tmp.printerfeatures.PostScript/default.plex.0.name", "default");
user_pref("print.tmp.printerfeatures.PostScript/default.plex.count", 1);
user_pref("print.tmp.printerfeatures.PostScript/default.resolution.0.name", "default");
user_pref("print.tmp.printerfeatures.PostScript/default.resolution.count", 1);
user_pref("print.tmp.printerfeatures.PostScript/default.supports_colorspace_change", false);
user_pref("print.tmp.printerfeatures.PostScript/default.supports_downloadfonts_change", false);
user_pref("print.tmp.printerfeatures.PostScript/default.supports_jobtitle_change", false);
user_pref("print.tmp.printerfeatures.PostScript/default.supports_orientation_change", true);
user_pref("print.tmp.printerfeatures.PostScript/default.supports_paper_size_change", true);
user_pref("print.tmp.printerfeatures.PostScript/default.supports_plex_change", false);
user_pref("print.tmp.printerfeatures.PostScript/default.supports_printincolor_change", true);
user_pref("print.tmp.printerfeatures.PostScript/default.supports_resolution_change", false);
user_pref("print.tmp.printerfeatures.PostScript/default.supports_spoolercommand_change", true);
user_pref("spellchecker.dictionary", "en_US");
