<?php
/**
 * Exception received by calling code when exception thrown in executed channel.
 *
 * @version    4.0.0
 * @package    MySource4
 * @subpackage Channels
 * @author     Squiz Pty Ltd <mysource4@squiz.net>
 * @copyright  2006-2007 Squiz Pty Ltd (ABN 77 084 670 600)
 * @license    http://matrix.squiz.net/licence Squiz.Net Open Source Licence
 */

/**
 * Exception received by calling code when exception thrown in executed channel.
 *
 * @since 4.0.0
 */
class ChannelException extends Exception
{


}//end class

?>
