<?php
/**
 * Exception thrown during the execution of an action.
 *
 * @version    4.0.0
 * @package    MySource4
 * @subpackage Channels
 * @author     Squiz Pty Ltd <mysource4@squiz.net>
 * @copyright  2006-2007 Squiz Pty Ltd (ABN 77 084 670 600)
 * @license    http://matrix.squiz.net/licence Squiz.Net Open Source Licence
 */

require_once dirname(__FILE__).'/ChannelException.inc';

/**
 * Exception thrown during the execution of an action.
 *
 * @since 4.0.0
 */
class ChannelActionException extends ChannelException
{


}//end class

?>
